def op_scan_int(self, instr):
        print("\tpush ebp")
        print("\tmov ebp,esp")
        loc = get_best_location(instr.inp1)
        print("\tpush " + instr.inp1)
        print("\tpush scan_int")
        print("\tcall scanf")
        print("\tadd esp, 8")
        print("\tmov esp, ebp")
print("\tpop ebp")